//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.detailOrders = new HashSet<detailOrders>();
            this.detailOrders1 = new HashSet<detailOrders>();
        }
    
        public string soDH { get; set; }
        public int idUser { get; set; }
        public string taiKhoan { get; set; }
        public Nullable<System.DateTime> ngayDat { get; set; }
        public Nullable<System.DateTime> ngayGiao { get; set; }
        public string diaChiGH { get; set; }
        public string tinhtrangDH { get; set; }
        public Nullable<int> idAdmin { get; set; }
    
        public virtual AdminAccounts AdminAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailOrders> detailOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailOrders> detailOrders1 { get; set; }
        public virtual tkNguoiDung tkNguoiDung { get; set; }
        public virtual Users Users { get; set; }
    }
}
