//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.detailOrders = new HashSet<detailOrders>();
            this.detailOrders1 = new HashSet<detailOrders>();
        }
    
        public string idSP { get; set; }
        public string nameSP { get; set; }
        public string imgSP { get; set; }
        public decimal priceSP { get; set; }
        public int typeSP { get; set; }
        public string noiDungSP { get; set; }
        public Nullable<int> idAdmin { get; set; }
    
        public virtual AdminAccounts AdminAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailOrders> detailOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailOrders> detailOrders1 { get; set; }
        public virtual typProducts typProducts { get; set; }
    }
}
