//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redstore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RedStore1Entities5 : DbContext
    {
        public RedStore1Entities5()
            : base("name=RedStore1Entities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminAccounts> AdminAccounts { get; set; }
        public virtual DbSet<detailOrders> detailOrders { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<tkNguoiDung> tkNguoiDung { get; set; }
        public virtual DbSet<typProducts> typProducts { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
